//This source code is generated by UI Designer Studio.

#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "UIGraphics.h"
#include "NVTToolCommand.h"
#include "UIFlowWndWrnMsgRes.c"
#include "UIFlowWndWrnMsg.h"
//---------------------UIFlowWndWrnMsgCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIFlowWndWrnMsg)
CTRL_LIST_ITEM(UIFlowWndWrnMsg_StatusTXT_Msg)
CTRL_LIST_END

//----------------------UIFlowWndWrnMsgCtrl Event---------------------------
INT32 UIFlowWndWrnMsg_OnOpen(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndWrnMsg_OnClose(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndWrnMsg_OnKeyEnter(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndWrnMsg_OnKeyMode(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndWrnMsg_OnKeyMenu(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndWrnMsg_OnKeyPlayback(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndWrnMsg_OnTimer(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIFlowWndWrnMsg)
EVENT_ITEM(NVTEVT_OPEN_WINDOW,UIFlowWndWrnMsg_OnOpen)
EVENT_ITEM(NVTEVT_CLOSE_WINDOW,UIFlowWndWrnMsg_OnClose)
EVENT_ITEM(NVTEVT_KEY_ENTER,UIFlowWndWrnMsg_OnKeyEnter)
EVENT_ITEM(NVTEVT_KEY_MODE,UIFlowWndWrnMsg_OnKeyMode)
EVENT_ITEM(NVTEVT_KEY_MENU,UIFlowWndWrnMsg_OnKeyMenu)
EVENT_ITEM(NVTEVT_KEY_PLAYBACK,UIFlowWndWrnMsg_OnKeyPlayback)
EVENT_ITEM(NVTEVT_TIMER,UIFlowWndWrnMsg_OnTimer)
EVENT_END

INT32 UIFlowWndWrnMsg_OnOpen(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_OPEN_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIFlowWndWrnMsg_OnClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_CLOSE_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIFlowWndWrnMsg_OnKeyEnter(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
INT32 UIFlowWndWrnMsg_OnKeyMode(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
INT32 UIFlowWndWrnMsg_OnKeyMenu(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
INT32 UIFlowWndWrnMsg_OnKeyPlayback(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
INT32 UIFlowWndWrnMsg_OnTimer(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
//----------------------UIFlowWndWrnMsg_StatusTXT_MsgCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndWrnMsg_StatusTXT_Msg)
EVENT_END

